PRODUCT_VERSION_MAJOR = 1
PRODUCT_VERSION_MINOR = 0
PRODUCT_VERSION_MAINTENANCE = 0
PRODUCT_VERSION_RELEASE = AR1

PRODUCT_BUILD_PROP_OVERRIDES += BUILD_DISPLAY_ID=ITL41F

PRODUCT_PROPERTY_OVERRIDES += \
	ro.modversion=TalonICS-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR).$(PRODUCT_VERSION_MAINTENANCE)-$(PRODUCT_VERSION_RELEASE)-DesireHD

